name: CI Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # Unit and module tests across platforms and Node versions
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [20.x, 22.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run ES module tests  
      run: npm run test:esm

    - name: Build ES modules
      run: |
        npm run build-es
        npm run build-server

  # E2E tests only on Ubuntu with latest Node (to save CI time)
  e2e-basic:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Install dependencies
      run: npm install

    - name: Run basic E2E tests
      run: npm run test:e2e:basic
      env:
        CI: true

  # Full E2E test suite (optional, can be enabled later)
  # e2e-full:
  #   runs-on: ubuntu-latest
  #   needs: e2e-basic
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #
  #   - name: Setup Node.js 22.x
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: 22.x
  #       cache: 'npm'
  #
  #   - name: Install dependencies
  #     run: npm ci
  #
  #   - name: Run full E2E test suite
  #     run: npm run test:e2e
  #     env:
  #       CI: true